Repository RustyNails8/readSAPEWA, pull requests merged in 2020-11, with the labels that each got.

#1 First script
  .gitignore
  scripts/readOlympusData.py
Labels: tutorial

#3 Get all EWA Status in CSV
  .gitignore
  scripts/GetRatinginCSV.py
Labels: enhancement

#4 Fix utf8 encoding
  scripts/GetRatinginCSV.py
Labels: bug

#5 Get data from EWA HTML tables
  docs/LINKS.md
  scripts/AnalyzeEWATables.md
  scripts/GetAllTables.py
  scripts/TableScrapeShort-2.py
Labels: enhancement
